import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ayyappan',
      email: 'ayyappan.sjec@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Croma Stores',
        logo: '/images/logo1.png',
        description: 'Best Seller',
        rating: 4.5,
        numReviews: 450,
      },
    },
    {
      name: 'Sundar',
      email: 'sundar@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Peter England Slim Shirt',
      category: 'Shirts',
      image: '/images/s1.jpg',
      price: 1299,
      countInStock: 23,
      brand: 'Peter England',  
      rating: 4.5,
      numReviews: 10,
      description: 'High in quality',
    },
    {
      name: 'Peter England Regular Shirt',
      category: 'Shirts',
      image: '/images/s2.jpg',
      price: 1099,
      countInStock: 45,
      brand: 'Peter England',
      rating: 4.0,
      numReviews: 10,
      description: 'High in quality',
    },
    {
      name: 'Peter England Fit Shirt',
      category: 'Shirts',
      image: '/images/s3.jpg',
      price: 899,
      countInStock: 50,
      brand: 'Peter England ',
      rating: 4.8,
      numReviews: 17,
      description: 'High in quality',
    },
    {
      name: 'Van Heusen Coat Pant Fit',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 3489,
      countInStock: 100,
      brand: 'Van Heusen',
      rating: 3.5,
      numReviews: 123,
      description: 'High in quality',
    },
    {
      name: 'Van Heusen Coat Pant Slim',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 2099,
      countInStock: 5,
      brand: 'Van Heusen',
      rating: 4.8,
      numReviews: 56,
      description: 'High in quality',
    },
    {
      name: 'Van Heusen Coat Pant Regular',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 1299,
      countInStock: 3,
      brand: 'Van Heusen',
      rating: 4.0,
      numReviews: 78,
      description: 'High in quality',
    },
  ],
};
export default data;
