import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ayyappan',
      email: 'ayyappan@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'sundar',
      email: 'sundar@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Mens Regular Formal Shirt',
      category: 'Mens Fashion',
      image: '/images/p1.jpg',
      price: 2359,
      countInStock: 15,
      brand: 'Peter England',
      rating: 4.1,
      numReviews: 23,
      description: 'High Quality Material',
    },
    {
      name: 'Mens Slim Fit Stretchable Jeans',
      category: 'Mens Fashion',
      image: '/images/p1.jpg',
      price: 1299,
      countInStock: 10,
      brand: 'Louis Philippe',
      rating: 4.6,
      numReviews:9,
      description: 'High Quality Material',
    },
    {
      name: 'Mens Regular Fit T-Shirt',
      category: 'Mens Fashion',
      image: '/images/p1.jpg',
      price: 699,
      countInStock: 18,
      brand: 'Peter England',
      rating: 4.54,
      numReviews: 19,
      description: 'High Quality Material',
    },
    {
      name: 'Woodentant women’s handloom cotton saree in multicolor designer Leaf in pallu withblouse piece',
      category: 'Womens Fashion',
      image: '/images/p1.jpg',
      price: 1280,
      countInStock: 6,
      brand: 'Woodentant',
      rating: 3.8,
      numReviews: 15,
      description: 'High Quality Material',
    },
    {
      name: 'Womens Cotton Anarkali Kurti (Red)',
      category: 'Womens Fashion',
      image: '/images/p1.jpg',
      price: 489,
      countInStock: 10,
      brand: 'Dipzonvilla',
      rating: 4.0,
      numReviews: 30,
      description: 'High Quality Material',
    },
    {
      name: 'Womens Regular Fit Top',
      category: 'Womens Fashion',
      image: '/images/p2.jpg',
      price: 1199,
      countInStock: 20,
      brand: 'StyleVille',
      rating: 4.0,
      numReviews: 18,
      description: 'High Quality Material',
    },
    {
      name: 'Apple iPhone 11 Pro Max (256GB) - Midnight Green',
      category: 'Mobiles',
      image: '/images/p3.jpg',
      price: 95900,
      countInStock: 4,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 124,
      description: 'High Quality Material',
    },
    {
      name: 'Samsung Galaxy Note 20 (Mystic Blue, 8GB RAM, 256GB Storage)',
      category: 'Mobiles',
      image: '/images/p4.jpg',
      price: 77999,
      countInStock: 7,
      brand: 'Samsung',
      rating: 4.7,
      numReviews: 17,
      description: 'High Quality Material',
    },
    {
      name: 'Vivo V21 5G (Sunset Dazzle, 8GB RAM, 128GB Storage)',
      category: 'Mobiles',
      image: '/images/p5.jpg',
      price: 29990,
      countInStock: 5,
      brand: 'Vivo',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Material',
    },
    {
      name: 'HP Pavilion (2021) Thin & Light 11th Gen Core i5 Laptop, 16 GB RAM, 512GB SSD, Iris Xe Graphics, 14-inch (35.56 cms) FHD Screen, Win 10, MS Office, Backlit Keyboard, Natural Silver (14-dv0054TU)',
      category: 'Laptops',
      image: '/images/p6.jpg',
      price: 67990,
      countInStock: 12,
      brand: 'HP',
      rating: 4.5,
      numReviews: 15,
      description: 'High Quality Material',
    },
    {
      name: 'Lenovo Yoga 7 11th Gen Intel Core i7 14" (35.56cms) Full HD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Fingerprint Reader/Slate Grey/Aluminium Surface/1.43Kg), 82BH004HIN',
      category: 'Laptops',
      image: '/images/p6.jpg',
      price: 97237,
      countInStock: 12,
      brand: 'Lenovo',
      rating: 4.8,
      numReviews: 15,
      description: 'High Quality Material',
    },
    {
      name: 'Acer Aspire 5 Thin and Light Laptop Intel Core I5 11th Gen ( 8 GB/512 GB SSD/ Windows 10 Home/ Iris Xe Graphic) A515-56-54FN with 39.6 cm (15.6 Inch) with FHD Display / 1.65 Kgs',
      category: 'Laptops',
      image: '/images/p6.jpg',
      price: 55990,
      countInStock: 8,
      brand: 'Acer',
      rating: 4.4,
      numReviews: 15,
      description: 'High Quality Material',
    },
  ],
};
export default data;
